name: Deploy to Google Cloud Run

on:
  push:
    paths:
      - assignment/app.py  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: teak-listener-435221-g2 
        service_account_key: ${{ secrets.GCP_SA_KEY }} 
        export_default_credentials: true

    - name: Authenticate Docker with GCR
      run: |
        echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build Docker image
      run: |
        docker build -t gcr.io/teak-listener-435221-g2/flask-api ./assignment

    - name: Push Docker image to GCR
      run: |
        docker push gcr.io/teak-listener-435221-g2/flask-api

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy flask-api \
          --image gcr.io/teak-listener-435221-g2/flask-api \
          --platform managed \
          --region us-east1 \
          --allow-unauthenticated
